// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import sitemap from '@astrojs/sitemap';
import mermaid from 'astro-mermaid';
import starlightLlmsTxt from 'starlight-llms-txt';
import tailwindcss from '@tailwindcss/vite';
import { visit } from 'unist-util-visit';

const BASE = '/learn-kaos';

// Starlight base-prefixes sidebar/nav links but NOT links written in page
// *content* (`[text](/path)` in md/mdx). This rehype plugin prepends the base
// to root-relative internal links so content links don't 404 on the project
// Pages site. (Hero `actions` are frontmatter, not content — they hardcode the
// base on the home page.)
function rehypeBaseLinks() {
  return (tree) => {
    visit(tree, 'element', (node) => {
      if (node.tagName !== 'a') return;
      const href = node.properties?.href;
      if (typeof href !== 'string') return;
      // root-relative, not external, not already based, not an anchor
      if (
        href.startsWith('/') &&
        !href.startsWith('//') &&
        href !== BASE &&
        !href.startsWith(BASE + '/')
      ) {
        node.properties.href = BASE + href;
      }
    });
  };
}

// Learn KAOS — Astro Starlight. Conventions match 273ventures.com:
// pnpm, Node 22, Tailwind v4 via @tailwindcss/vite, ~/@ -> src aliases.
// Sidebar grows as milestones land (M0 ships Start-here + Gallery).
// https://astro.build/config
export default defineConfig({
  site: 'https://273v.github.io',
  base: BASE,
  trailingSlash: 'never',

  markdown: {
    rehypePlugins: [rehypeBaseLinks],
  },

  integrations: [
    // Mermaid must come before Starlight so it transforms ```mermaid blocks
    // before Expressive Code claims them. Renders client-side (no build browser).
    mermaid({
      theme: 'neutral',
      autoTheme: true,
    }),
    starlight({
      title: 'Learn KAOS',
      description:
        'Tested, multi-learner docs and one-command runnable examples for the open-source KAOS (Kelvin Agentic OS) ecosystem.',
      customCss: ['./src/styles/global.css'],
      // Quality-of-life features standard on well-built docs (e.g. the Astro
      // docs themselves): a per-page "edit on GitHub" link, last-updated dates
      // from git history, and prev/next pagination.
      routeMiddleware: './src/routeData.ts',
      editLink: {
        baseUrl: 'https://github.com/273v/learn-kaos/edit/main/',
      },
      lastUpdated: true,
      pagination: true,
      // KAOS's audience includes AI agents, so make the docs first-class LLM
      // context: /llms.txt (index) + /llms-full.txt (the whole site concatenated)
      // for one-shot ingestion. Generated from the content collection.
      plugins: [
        starlightLlmsTxt({
          projectName: 'Learn KAOS',
          description:
            'Tested, multi-learner docs and one-command runnable examples for the open-source KAOS (Kelvin Agentic OS) ecosystem.',
        }),
      ],
      // Polished, copy-friendly code blocks (Expressive Code ships the copy
      // button + frames; this adds a matched theme pair, soft frames, and a
      // word-wrap toggle so long one-liners never need horizontal scrolling).
      expressiveCode: {
        themes: ['github-dark-default', 'github-light-default'],
        styleOverrides: {
          borderRadius: '0.5rem',
          frames: {
            shadowColor: 'rgba(15, 23, 42, 0.10)',
          },
        },
        defaultProps: {
          wrap: true,
          overridesByLang: {
            'bash,sh,zsh': { frame: 'terminal' },
          },
        },
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/273v/learn-kaos' },
      ],
      sidebar: [
        {
          label: 'Start here',
          items: [
            { label: 'What is KAOS?', slug: 'what-is-kaos' },
            { label: 'How KAOS fits together', slug: 'architecture' },
            { label: 'Pick your path', slug: 'learning-paths' },
            { label: 'Install', slug: 'get-started/install' },
            { label: 'Your first example', slug: 'get-started/first-example' },
            { label: 'FAQ', slug: 'faq' },
          ],
        },
        {
          label: 'Tutorials',
          items: [{ autogenerate: { directory: 'tutorials' } }],
        },
        {
          label: 'How-to',
          // Grouped (not autogenerated) so 46 recipes are scannable by task area.
          items: [
            {
              label: 'Ingest & extract',
              items: [
                'how-to/ingest-a-pdf',
                'how-to/ingest-office-docs',
                'how-to/web-page-to-ast',
                'how-to/parse-email',
                'how-to/triage-before-ingest',
                'how-to/detect-pages-needing-ocr',
                'how-to/pull-a-sec-filing',
                'how-to/redline-a-contract',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'Search, NLP & graph',
              items: [
                'how-to/search-text-with-bm25',
                'how-to/semantic-embeddings',
                'how-to/chunk-a-document',
                'how-to/find-near-duplicates',
                'how-to/cluster-a-corpus',
                'how-to/find-financial-terms',
                'how-to/extract-entities',
                'how-to/detect-and-redact-pii',
                'how-to/parse-legal-citations',
                'how-to/extract-citations',
                'how-to/extract-contract-definitions',
                'how-to/check-for-conflicts',
                'how-to/rank-a-graph',
                'how-to/run-sql-analytics',
                'how-to/query-the-session-graph',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'LLM programming & agents',
              items: [
                'how-to/optimize-a-program',
                'how-to/cap-llm-cost',
                'how-to/provider-failover',
                'how-to/use-a-local-model',
                'how-to/prefetch-models',
                'how-to/choose-a-pattern',
                'how-to/configure-permissions',
                'how-to/review-a-contract',
                'how-to/research-over-a-corpus',
                'how-to/delegate-and-handoff',
                'how-to/pause-and-resume',
                'how-to/export-otel',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'Serve, deploy & data',
              items: [
                'how-to/connect-an-ai-tool',
                'how-to/serve-over-http',
                'how-to/deploy-an-app',
                'how-to/inspect-a-runtime',
                'how-to/generate-synthetic-data',
                'how-to/analyze-billing',
                'how-to/use-kl3m-data',
                'how-to/generate-session-names',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'Extend KAOS',
              items: [
                'how-to/add-a-template-kind',
                'how-to/add-typed-settings',
                'how-to/test-your-own-snippets',
              ].map((slug) => ({ slug })),
            },
          ],
        },
        {
          label: 'Concepts',
          // Grouped in learning order rather than alphabetical.
          items: [
            {
              label: 'Foundations & runtime',
              items: [
                'concepts/why-di-over-globals',
                'concepts/settings-resolution',
                'concepts/artifact-size-ladder',
                'concepts/determinism-contract',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'The document model',
              items: [
                'concepts/one-document-model',
                'concepts/block-vs-inline',
                'concepts/provenance-and-the-producer-contract',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'LLM programming',
              items: [
                'concepts/the-offline-seam',
                'concepts/transport-vs-programming',
                'concepts/typed-llm-programming',
                'concepts/structured-output-modes',
                'concepts/optimizers-and-budget',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'Agents & memory',
              items: [
                'concepts/agent-vs-runner',
                'concepts/the-8-step-turn-loop',
                'concepts/memory-as-context-assembly',
                'concepts/events-and-spans',
                'concepts/anatomy-of-single-user-chat',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'Trust, grounding & cost',
              items: [
                'concepts/grounding-and-verification',
                'concepts/the-refusal-contract',
                'concepts/why-plain-bm25',
                'concepts/cost-as-a-contract',
                'concepts/is-kaos-trustworthy',
              ].map((slug) => ({ slug })),
            },
            {
              label: 'Safety & serving',
              items: [
                'concepts/session-enforcement',
                'concepts/untrusted-input-defenses',
                'concepts/the-audit-trail',
                'concepts/the-mcp-bridge',
              ].map((slug) => ({ slug })),
            },
          ],
        },
        {
          label: 'Reference',
          items: [{ autogenerate: { directory: 'reference' } }],
        },
        {
          label: 'Use cases',
          items: [{ label: 'Legal & financial use cases', slug: 'use-cases' }],
        },
        {
          label: 'Examples gallery',
          items: [{ label: 'Gallery', slug: 'gallery' }],
        },
      ],
    }),
    sitemap(),
  ],

  vite: {
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        '~': new URL('./src', import.meta.url).pathname,
        '@': new URL('./src', import.meta.url).pathname,
        // depth-independent imports of the tested source-of-truth files
        // (rendered into MDX via `?raw` so shown == tested).
        '#examples': new URL('./examples', import.meta.url).pathname,
        '#snippets': new URL('./snippets', import.meta.url).pathname,
      },
    },
  },
});
