#!/usr/bin/env python3
"""reference-gen: regenerate the generated Reference pages from source-of-truth.

Per LEARN_KAOS_PLAN.md, generated reference must never be hand-typed — so the
docs cannot drift from reality. CI runs this and then `git diff --exit-code`,
which fails if the committed output is stale (someone edited the .mdx instead
of the source).

Generated now:
  reference/packages  <- scripts/packages.toml (the canonical package map)

The output is deterministic given the committed source (live PyPI versions are
rendered as shields.io badges resolved in the browser, never baked in), so the
CI drift check is stable.

Usage:
  python3 scripts/gen_reference.py            # regenerate
  python3 scripts/gen_reference.py --check     # exit 1 if output would change
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGES_TOML = ROOT / "scripts" / "packages.toml"
OUT = ROOT / "src" / "content" / "docs" / "reference" / "packages.mdx"

LAYERS = [
    ("apps", "Apps & serving"),
    ("agents", "Agents"),
    ("llm", "LLM programming"),
    ("ingestion", "Ingestion & data"),
    ("substrate", "Deterministic substrate"),
    ("foundation", "Foundation"),
]

HEADER = """\
---
title: Package reference
description: Every public kaos-* package, its layer, CLI, and live version. Generated — do not edit by hand.
---

{/* GENERATED by scripts/gen_reference.py from scripts/packages.toml. Do not edit. */}

The KAOS ecosystem is a set of small, composable packages. Edit the source list
(`scripts/packages.toml`) and regenerate — this page can't drift from it (CI checks).
Versions are live from PyPI. See [how it all fits together](/architecture) for the
layered view.
"""


def badge(name: str) -> str:
    pv = f"https://img.shields.io/pypi/v/{name}.svg"
    pypi = f"https://pypi.org/project/{name}/"
    return f"[![PyPI]({pv})]({pypi})"


def render(packages: list[dict]) -> str:
    out = [HEADER]
    by_layer: dict[str, list[dict]] = {}
    for p in packages:
        by_layer.setdefault(p["layer"], []).append(p)
    for key, title in LAYERS:
        rows = by_layer.get(key, [])
        if not rows:
            continue
        out.append(f"\n## {title}\n")
        out.append("| Package | Version | CLI | What it does |")
        out.append("|---|---|---|---|")
        for p in rows:
            repo = f"https://github.com/273v/{p['name']}"
            cli = f"`{p['cli']}`" if p.get("cli") else "—"
            out.append(
                f"| [{p['name']}]({repo}) | {badge(p['name'])} | {cli} | {p['summary']} |"
            )
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    packages = tomllib.loads(PACKAGES_TOML.read_text(encoding="utf-8")).get("package", [])
    rendered = render(packages)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
    if "--check" in argv:
        if current != rendered:
            print("reference-gen: reference/packages.mdx is STALE — run gen_reference.py", file=sys.stderr)
            return 1
        print("reference-gen: reference/packages.mdx is up to date.")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"reference-gen: wrote {OUT.relative_to(ROOT)} ({len(packages)} packages).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
