#!/usr/bin/env python3
"""reference-gen: regenerate the generated Reference pages from source-of-truth.

Per LEARN_KAOS_PLAN.md, generated reference must never be hand-typed — so the
docs cannot drift from reality. CI runs this and then `git diff --exit-code`,
which fails if the committed output is stale (someone edited the .mdx instead
of the source).

Generated now:
  reference/packages  <- scripts/packages.toml (the canonical package map)

The output is deterministic given the committed source (live PyPI versions are
rendered as shields.io badges resolved in the browser, never baked in), so the
CI drift check is stable.

Usage:
  python3 scripts/gen_reference.py            # regenerate
  python3 scripts/gen_reference.py --check     # exit 1 if output would change
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGES_TOML = ROOT / "scripts" / "packages.toml"
CLI_TOML = ROOT / "scripts" / "cli.toml"
REF = ROOT / "src" / "content" / "docs" / "reference"
OUT = REF / "packages.mdx"
CLI_OUT = REF / "cli.mdx"

LAYERS = [
    ("apps", "Apps & serving"),
    ("agents", "Agents"),
    ("llm", "LLM programming"),
    ("ingestion", "Ingestion & data"),
    ("substrate", "Deterministic substrate"),
    ("foundation", "Foundation"),
]

HEADER = """\
---
title: Package reference
description: Every public kaos-* package, its layer, CLI, and live version. Generated — do not edit by hand.
---

{/* GENERATED by scripts/gen_reference.py from scripts/packages.toml. Do not edit. */}

The KAOS ecosystem is a set of small, composable packages. Edit the source list
(`scripts/packages.toml`) and regenerate — this page can't drift from it (CI checks).
Versions are live from PyPI. See [how it all fits together](/architecture) for the
layered view.
"""


def badge(name: str) -> str:
    pv = f"https://img.shields.io/pypi/v/{name}.svg"
    pypi = f"https://pypi.org/project/{name}/"
    return f"[![PyPI]({pv})]({pypi})"


def render(packages: list[dict]) -> str:
    out = [HEADER]
    by_layer: dict[str, list[dict]] = {}
    for p in packages:
        by_layer.setdefault(p["layer"], []).append(p)
    for key, title in LAYERS:
        rows = by_layer.get(key, [])
        if not rows:
            continue
        out.append(f"\n## {title}\n")
        out.append("| Package | Version | CLI | What it does |")
        out.append("|---|---|---|---|")
        for p in rows:
            repo = f"https://github.com/273v/{p['name']}"
            cli = f"`{p['cli']}`" if p.get("cli") else "—"
            out.append(
                f"| [{p['name']}]({repo}) | {badge(p['name'])} | {cli} | {p['summary']} |"
            )
    out.append("")
    return "\n".join(out)


CLI_HEADER = """\
---
title: CLI reference
description: Every kaos-* command-line tool and its subcommands. Generated — do not edit by hand.
---

{/* GENERATED by scripts/gen_reference.py from scripts/cli.toml. Do not edit. */}

Every package ships a CLI (and most a matching `kaos-*-serve` MCP server). Run
`kaos-<tool> --help`, or `kaos-<tool> <command> --help`, for full usage. All follow the
same conventions: `--json` for structured output, human-readable by default, errors to
stderr. See the [package reference](/reference/packages) for versions and install.

| Tool | Subcommands | What it does |
|---|---|---|
"""


def render_cli(clis: list[dict]) -> str:
    rows = [CLI_HEADER]
    for c in clis:
        cmds = " ".join(f"`{x}`" for x in c["commands"])
        rows.append(f"| `{c['name']}` | {cmds} | {c['note']} |")
    rows.append("")
    return "\n".join(rows)


def _emit(out: Path, rendered: str, check: bool, label: str) -> int:
    out.parent.mkdir(parents=True, exist_ok=True)
    current = out.read_text(encoding="utf-8") if out.is_file() else ""
    if check:
        if current != rendered:
            print(f"reference-gen: {label} is STALE — run gen_reference.py", file=sys.stderr)
            return 1
        return 0
    out.write_text(rendered, encoding="utf-8")
    return 0


def main(argv: list[str]) -> int:
    check = "--check" in argv
    packages = tomllib.loads(PACKAGES_TOML.read_text(encoding="utf-8")).get("package", [])
    clis = tomllib.loads(CLI_TOML.read_text(encoding="utf-8")).get("cli", [])
    rc = _emit(OUT, render(packages), check, "reference/packages.mdx")
    rc |= _emit(CLI_OUT, render_cli(clis), check, "reference/cli.mdx")
    if check:
        if rc == 0:
            print("reference-gen: generated reference is up to date.")
        return rc
    print(f"reference-gen: wrote packages.mdx ({len(packages)}) + cli.mdx ({len(clis)}).")
    return rc


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
